### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by AmePizza** [enjarai/show-me-your-skin#8]
If I try to open the config with Mod Menu or press the keybind (Basically try to use the mod in general) it crashes the game completely. Crash report says something about Rendering entity in world even though I wasn't in a world yet, plus "Cannot invoke "net.minecraft.class_1297.method_23317()" because "$$0" is null"

**Comment by enjarai** [comment]
Please provide the full crash report and logs, this looks like a mod conflict of some kind.

**Comment by erxson** [comment]
[[10:32:44] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5321.method_29177()" because "worldKey" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:78) ~[Bobby.jar:?]
	at net.minecraft.client.world.ClientChunkManager.handler$zcp000$bobbyInit(ClientChunkManager:1053) ~[?:?]
	at net.minecraft.client.world.ClientChunkManager.<init>(ClientChunkManager:42) ~[?:?]
	at net.minecraft.client.world.ClientWorld.<init>(ClientWorld:120) ~[?:?]
	at nl.enjarai.showmeyourskin.client.DummyClientWorld.<init>(DummyClientWorld.java:17) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientWorld.getInstance(DummyClientWorld.java:12) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:35) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.client.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:30) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.config.ModConfig.getGlobalScreen(ModConfig.java:63) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.client.ModKeyBindings.tick(ModKeyBindings.java:24) ~[Krasivo_ShowMeYourSkin.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkin.tick(ShowMeYourSkin.java:25) ~[Krasivo_ShowMeYourSkin.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[fabric-lifecycle-events-v1-2.0.4+d8d7804a60-d80747583937e2d1.jar:?]
	at net.minecraft.client.MinecraftClient.handler$cck000$onEndTick(MinecraftClient:11972) ~[?:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1817) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[NotEnoughCrashes.jar:?]
	at net.minecraft.client.MinecraftClient.modify$ebg000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24521) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:764) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[NotEnoughCrashes.jar:?]
	at net.minecraft.client.MinecraftClient.modify$ebg000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24521) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:764) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[NotEnoughCrashes.jar:?]
	at net.minecraft.client.MinecraftClient.modify$ebg000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:24510) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:759) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]](https://bytebin.lucko.me/oFGBJgB6pa)

**Comment by enjarai** [comment]
> https://bytebin.lucko.me/oFGBJgB6pa

Please dont hijack other issues with your own crash report. Besides, this crash was fixed in the latest version, see #7

**Comment by enjarai** [comment]
> https://pastebin.com/fDdkgzxn

This seems to be an incompatibility with the "Essential" mod, which from what I can tell, is closed source. This will make it difficult for me to fix any issues related to it, but I'll see what I can do if I have the time.

**Comment by AmePizza** [comment]
Ah, I see. Now that you mention it I do see that mod showing up in the log. Well, good luck! Thank you for taking the time.

**Comment by enjarai** [comment]
After looking into it, it's basically impossible for me to fix this without being able to see the source code of Essential. The only solution I see is to have them fix it on their side, which should be very easy for them to do, looking at the crash report.

I'll close this issue since I'm pretty sure theres nothing I can do to fix it.
