### ISSUE TITLE
Crash [log]

### ISSUE THREAD

**Issue by ardissaps** [enjarai/show-me-your-skin#9]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/31/22, 7:43 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'elytratrinket'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$ecj000$catchFabricInit(class_310.java:18953)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'elytratrinket'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of top.theillusivec4.elytratrinket.client.ElytraTrinketRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [showmeyourskin.compat.elytratrinket.mixins.json:ElytraTrinketRendererMixin from mod showmeyourskin] from phase [DEFAULT] in config [showmeyourskin.compat.elytratrinket.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on hideElytra could not find any targets matching 'render(Lnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/VertexConsumerProvider;ILnet/minecraft/entity/LivingEntity;FFFFFF)V' in top.theillusivec4.elytratrinket.client.ElytraTrinketRenderer. Using refmap show-me-your-skin-refmap.json [PREINJECT Applicator Phase -> showmeyourskin.compat.elytratrinket.mixins.json:ElytraTrinketRendererMixin from mod showmeyourskin -> Prepare Injections ->  -> handler$ela001$hideElytra(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_1309;FFFFFFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.client.MinecraftClient.redirect$ecj000$catchFabricInit(MinecraftClient:18953)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452)
	at net.minecraft.client.main.Main.main(Main:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
	at net.minecraft.class_310.redirect$ecj000$catchFabricInit(class_310.java:18955)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 950849960 bytes (906 MiB) / 1610612736 bytes (1536 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x17c8
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 25038.26
	Virtual memory used (MB): 11277.16
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 163.68
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx6144M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		additionalstructures: Additional Structures 3.0.3
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		advancementplaques: Advancement Plaques 1.4.4
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		amecs: Amecs 1.3.7+mc.1.18.2
			amecsapi: Amecs API 1.3.5+mc22w06a
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		animatica: Animatica 0.4+1.18
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.4.68
		attributefix: AttributeFix 14.0.2
		autorun: AutoRun 0.4.0
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 1.4.6
		better_runtime_resource_pack: Better Runtime Resource Pack 0.6.2
			advanced_runtime_resource_pack: Advanced Runtime Resource Pack 0.6.2
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.0
		betterf3: BetterF3 1.2.5
		betterfpsdist: Better FPS distance Mod 1.18-1.7
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.3
		betternether: Better Nether 6.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.7.3
		blanket-client-tweaks: Blanket Client-tweaks 1.0.3
		boathud: BoatHud 1.1.0
		bookshelf: Bookshelf 13.1.16
		brb: Better Recipe Book 1.5.6
		byg: Oh The Biomes You'll Go 1.4
		campanion: Campanion 3.0.4
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		cem: Custom Entity Models 0.7.1
		chime: Chime 1.2.1
		citresewn: CIT Resewn 1.0.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-api: Cloth API 3.2.64
			cloth-basic-math: cloth-basic-math 0.6.0
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+8
		collective-fabric: Collective (Fabric) 4.26
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.1+mc.1.18.2
		command_structures: Command Structures 2.0.1+1.18.2
		completeconfig: CompleteConfig 1.4.1
		continuity: Continuity 1.1.0+1.18.2
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.6.11
		creeperoverhaul: Creeper Overhaul 1.3.1
		cullleaves: Cull Leaves 2.3.2
		debugify: Debugify 1.10.0
		dimores: DimensionalOres 1.0.2
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchdesc: EnchantmentDescriptions 10.0.3
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		entity_texture_features: Entity Texture Features 3.0.2
		entityculling: EntityCulling-Fabric 1.5.1
		expandeddelight: Expanded Delight 0.1.5
		extrasounds: Extra Sounds 2.2.1+1.18.2
			soundcategories: Sound Categories 1.2.1+1.18
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.6
		fabricskyboxes: FabricSkyBoxes 0.5.5
		fallingtree: FallingTree 3.5.1
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.1.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		fps: FPS Monitor 1.18-1.2.1-Fabric
		freecam: Freecam 1.0.6
		friendsandfoes: Friends&Foes 1.4.2
		fvt: Flour's Various Tweaks 1.10.0-mc1.18.2
		gammautils: Gamma Utils 1.5.7
		geckolib3: Geckolib 3.0.42
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		global-datapack: Global Datapack 1.0
		goodall: Goodall 1.0.2
		graveyard: The Graveyard 1.8
			omega-config: OmegaConfig 1.2.2-1.18.1
		iceberg: Iceberg 1.0.38
		incendium: Incendium + Seed Fix 5.0.3
		indium: Indium 1.0.3+mc1.18.2
		inspecio: Inspecio 1.3.0+1.18
			fabric-rendering-v1: Quilted Fabric Rendering (v1) 2.0.0+1.18.2-SNAPSHOT
				quilt_tooltip: Quilt Tooltip API 1.0.0+1.18.2-SNAPSHOT
			quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
				quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
				quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
				quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
				quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
			quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.0+1.18.2-SNAPSHOT
				quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.0
		iris: Iris 1.2.4-build.38
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		keymap: KeyMap 0.4.2-beta.3+1.18.1-fabric
			org_yaml_snakeyaml: snakeyaml 1.30
		ksyxis: Ksyxis 1.1
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		llamarama: Llamarama 1.7.0
		loadingscreentips: Loading Tips 1.0.1
		malilib: MaLiLib 0.12.1
		mca: Minecraft Comes Alive 7.3.0
		mcpppp: MCPPPP 0.7.1
		megane: megane 7.5.1
			megane-api: megane-api 7.1.0
			megane-fabric-transfer: megane-fabric-transfer 7.1.0
			megane-runtime: megane-runtime 7.2.0
			megane-vanilla: megane-vanilla 7.1.1
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.2
		modsettings: ModSettings 1.1.0+1.18.1
		moremcmeta: MoreMcmeta 1.18.2-3.0.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mythicmounts: Mythic Mounts 1.18.2-7.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		patchouli: Patchouli 1.18.2-69-FABRIC
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		prefab: Prefab 3.1.5
		presencefootsteps: Presence Footsteps 1.5.0
			kirin: Kirin UI 1.10.0
		puzzle: Puzzle 1.2.1
			midnightlib: MidnightLib 0.4.0
			puzzle-base: Puzzle Base 1.2.1
			puzzle-gui: Puzzle GUI 1.2.1
			puzzle-models: Puzzle Models 1.2.1
			puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		puzzleslib: Puzzles Lib 3.3.5
		quickshulker: Quick Shulker 1.3.6-1.18
			kyrptconfig: Kyrpt Config 1.3.4-1.18
				blue_endless_jankson: jankson 1.2.1
			shulkerutils: shulkerutils 1.0.4-1.18
		reasonable-sorting: Reasonable Sorting 1.5
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		repurposed_structures: Repurposed Structures 4.1.10+1.18.2
		respackopts: Resource Pack Options 2.10.2
			com_github_meteordevelopment_starscript: starscript 0.1.9
			libjf-base: LibJF Base 2.8.1
			libjf-data-manipulation-v0: LibJF Data Manipulation 2.8.1
			libjf-unsafe-v0: LibJF Unsafe 2.8.1
		roughlyenoughitems: Roughly Enough Items 8.2.470
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		seedfix: Seed Fix 1.0.1
		showmeyourskin: Show Me Your Skin! 1.1.1+1.18.2
		shwfox: Shadew's Foxes 1.3+fabric
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		spoornweaponattributes: SpoornWeaponAttributes 3.4
			net_objecthunter_exp4j: exp4j 0.4.8
		stoneholm: Stoneholm 1.4.3
		suggestion_tweaker: Suggestion Tweaker 1.18.2-1.2.0
		t_and_t: Towns and Towers - Structure Add-on 1.6
		terrablender: TerraBlender 1.1.0.101
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		tputils: TP Utils 1.5.12
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.1
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		tweakermore: TweakerMore 3.3.0
			conditional-mixin: conditional mixin 0.3.0
		vanityslots: Vanity Slots 1.1.2
		waystones: Waystones 2.5.3
		weaponmaster: YDM's Weapon Master 1-18-x
		whats_that_slot: What's That Slot? 1.2.3+1.18.1
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		wthit: wthit 4.10.3
		wthit-plugins: Wthit Plugins 1.0.5
		xaerominimap: Xaero's Minimap 22.8.2
		xaeroworldmap: Xaero's World Map 1.22.0
		xtraarrows: Xtra Arrows 1.8.3
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
		zoomify: Zoomify 1.6.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: None

**Comment by enjarai** [comment]
Fixed in 1.1.2
